stages:
  train:
    cmd: python scripts/train.py
    deps:
      - data/heart_disease.csv
      - scripts/train.py
      - params.yaml
    outs:
      - models/xgboost_model.pkl
    metrics:
      - artifacts/metrics.json
